version: '3.7'
services:

  mariadb:
    image: mariadb:10.4.6
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=test
    volumes:
     - ./db/conf.d:/etc/mysql/conf.d
     - ./db/data:/var/lib/mysql
    privileged: true
    ports:
     - '3306:3306'